module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "bg-primary",
    "bg-secondary",
    "bg-accent",
    "bg-success",
    "bg-warn",
    "bg-danger",
    "bg-base",
    "bg-surface",
    "bg-card",
    "text-primary",
    "text-secondary",
    "text-accent",
    "text-success",
    "text-warn",
    "text-danger",
    "text-base",
    "text-surface",
    "text-card",
    "border-primary",
    "border-secondary",
    "border-accent",
    "border-success",
    "border-warn",
    "border-danger",
    "border-base",
    "border-surface",
    "border-card",
  ],
  theme: {
    extend: {
      colors: {
        "deep-900": "#0B0F1A",
        "deep-800": "#10172A",
        "deep-700": "#182138",
        "gold-500": "#D4AF37",
        "amber-400": "#FFBF00",
        "iris-100": "#D4D8FF",
        "iris-200": "#BFC6FF",
        sand: "#EDE9E3",
      },
    },
  },
  plugins: [],
};
